# Generated by Django 5.2.14 on 2026-06-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'الدفع عند الاستلام (Cash on Delivery)'), ('Card', 'البطاقة البنكية (Credit Card)')], default='COD', max_length=20),
        ),
    ]
